// apps/vue-app/src/views/second.vue
<template>
    <!-- eslint-disable max-len -->
  <div class="container py-5">
  <div class="p-5 mb-5 bg-dark rounded-3 d-flex flex-column align-items-center">
    <h1 class="pb-5 text-white">Vue.js 3.0.0</h1>
    <button class="btn btn-secondary mx-2" type="button" @click="$router.push('/')">Go to home page</button>
  </div>
</div>
</template>

// apps/angular-app/src/app/second/second.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-second',
  templateUrl: './second.component.html',
  styleUrls: ['./second.component.css']
})
export class SecondComponent implements OnInit {
  title = 'Angular 14.0.0';

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container py-5">
  <div class="p-5 mb-5 bg-dark rounded-3 d-flex flex-column align-items-center">
    <h1 class="pb-5 text-white">{{title}}</h1>
    <button class="btn btn-secondary mx-2" type="button" routerLink="/home">Go to home page</button>
  </div>
</div>
